export const WALLET_DEPOSIT_MASTER_FUND = process.env.WALLET_DEPOSIT_MASTER_FUND;
export const ADDRESS_BUY_CARD = process.env.ADDRESS_BUY_CARD;
export const CONTRACT_ADDRESS_USDT = process.env.CONTRACT_ADDRESS_USDT;
export const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY || '';
export const ETHERSCAN_API_KEY_2 = process.env.ETHERSCAN_API_KEY_2 || '';


export const APP_ACTION = {
  HANDLE_EXCEPTION: 'HANDLE_EXCEPTION',
  HANDLE_REQUEST: 'HANDLE_REQUEST',
  HANDLE_RESPONSE: 'HANDLE_RESPONSE',
};

export const ERR_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  MISSING_ENV_VARIABLE: 'MISSING_ENV_VARIABLE',
  INVALID_WALLET_ADDRESS: 'INVALID_WALLET_ADDRESS',
  INVALID_CONTRACT_ADDRESS: 'INVALID_CONTRACT_ADDRESS',
  ETHERSCAN_API_ERROR: 'ETHERSCAN_API_ERROR',
};

export const HEADER_KEY = { LOG_ID: 'log-id' };

export const INJECTION_TOKEN = {
  AUDIT_SERVICE: 'AUDIT_SERVICE',
};
